apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-producer-deployment
  labels: 
    app: employee-producer-label
    type: employee-data-rs
spec:
  template:
    metadata:
      name: employee-producer-pod
      labels: 
        app: employee-producer-label
        type: employee-data-service
    spec:
      containers:
      - name: employee-producer-pod
        image: azurecloud1/employee-producer:1.0-amd64
        ports:
        - containerPort: 8000

  replicas: 3 
  selector:
   matchLabels:
      type: employee-data-service



 
        