apiVersion: v1
kind: Pod
metadata:
  name: employee-cert-pod
  namespace: resourcelimit
  labels: 
    app: employee-cert-label
    type: employee-cert-service
spec:
  containers:
    - name: employee-cert-pod
      image: azurecloud1/employee-cert:1.0-amd64
      ports:
      - containerPort: 9000
      resources:
          requests:
            cpu: 200m
            memory: 0.5Gi
          limits:
            cpu: 400m
            memory: 1Gi



 
        