apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-app-perc
  labels:
    app: echo-application
    env: test
    version: v1.0.0
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      # The default value is 25%.
      # maxUnavailable is an optional field that specifies the maximum number of Pods that can be unavailable during the update process.
      maxUnavailable: 20% # The value can be an absolute number (for example, 5) or a percentage of desired Pods (for example, 10%). 
      # maxSurge is an optional field that specifies the maximum number of Pods that can be created over the desired number of Pods.
      maxSurge: 20% # The value can be an absolute number (for example, 5) or a percentage of desired Pods (for example, 10%). 
  replicas: 5
  selector:
    matchLabels:
      app: echo-application
      env: test
  template:
    metadata:
      labels:
        app: echo-application
        env: test
        version: v1.0.0
    spec:
      containers:
      - name: echoapp
        image: azurecloud1/employee-producer:v1.0.0
        ports:
        - containerPort: 8000
        startupProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: echoapp-svc
spec:
  selector:
    app: echo-application
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  type: NodePort