apiVersion: v1
kind: Pod
metadata:
  name: "{{.Values.EmployeePodName}}" 
  labels: 
    app: employee-producer-label
    type: employee-data-service
spec:
  containers:
    - name: employee-producer-pod
      image: "{{.Values.EmployeeImageName}}"   
      ports:
      - containerPort: {{.Values.containerPort}}
