apiVersion: v1
kind: Pod
metadata:
  name: payment-processing-pod-configmap
  labels: 
    app: payment-processing-label
    type: payment-processing
spec:
  containers:
    - name: payment-processing-pod
      image: azurecloud1/employee-producer:1.0-amd64
      ports:
        - containerPort: 9000
      envFrom:
        - configMapRef:
            name: payment-processing-config
